import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-sans",
  subsets: ["cyrillic", "latin"],
  weight: ["300", "400", "500", "600"],
  preload: true,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body
        className={`${ibmPlexSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
