import { IBM_Plex_Sans, IBM_Plex_Serif } from "next/font/google";
import { Footer, Header } from "@/widgets";
import { MotionProvider } from "@/components";
import "./globals.css";

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-sans",
  subsets: ["cyrillic", "latin"],
  weight: ["300", "400", "500", "600", "700"],
  preload: true,
});

const ibmPlexSerif = IBM_Plex_Serif({
  variable: "--font-ibm-serif",
  subsets: ["cyrillic", "latin"],
  weight: ["700"],
  preload: true,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body
        className={`${ibmPlexSans.variable} ${ibmPlexSerif.variable} antialiased`}
      >
        <MotionProvider>
          {/* <Header /> */}
          {children}
          <Footer />
        </MotionProvider>
      </body>
    </html>
  );
}
